version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__MySQLConnection: "Server=db; Database=storedb; User=root; Password=W@lter1991; Port=3306"
    depends_on:
      - db

  dbbusca en documentos un archivo :
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: W@lter1991
      MYSQL_DATABASE: storedb
    ports:
      - "3307:3306" # Mapeado a 3307 en el host para evitar conflictos
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
